from flask import Flask, abort, render_template


app = Flask(__name__)

LEGACY_FLOWERS = [
    {
        "slug": "sunset-dahlia",
        "name": "Sunset Dahlia",
        "type": "Dahlia pinnata",
        "location": "Highland garden, Mexico",
        "status": "In bloom",
        "color": "Coral orange",
        "bloom_season": "Mid-summer to autumn",
        "height": "90–120 cm",
        "sunlight": "Full sun",
        "water": "Regular, well-drained",
        "origin": "Mexico and Central America",
        "image": "https://images.unsplash.com/photo-1508808703027-4e8e8e8b1b72?auto=format&fit=crop&w=1800&q=85",
        "accent": "amber",
        "summary": "A layered, sun-loving bloom with warm sunset tones and a long flowering window for late-season gardens.",
        "description": "Sunset Dahlia forms full, dinner-plate blooms on sturdy stems and rewards regular picking with more flowers. Give it rich soil, morning light, and a little shelter from strong wind so the tall stems can hold their shape.",
        "highlights": ["Pollinator-friendly bloom", "Pinch young plants for fullness", "Lift tubers after first frost"],
    },
    {
        "slug": "blue-moon-hydrangea",
        "name": "Blue Moon Hydrangea",
        "type": "Hydrangea macrophylla",
        "location": "Misty coast, Japan",
        "status": "In bloom",
        "color": "Cornflower blue",
        "bloom_season": "Early summer to fall",
        "height": "90–150 cm",
        "sunlight": "Morning sun, afternoon shade",
        "water": "Consistently moist",
        "origin": "Japan and Korea",
        "image": "https://images.unsplash.com/photo-1561181286-d3fee7d55364?auto=format&fit=crop&w=1800&q=85",
        "accent": "teal",
        "summary": "A generous globe of blue florets that brings a cool, cloud-like presence to shaded summer borders.",
        "description": "Blue Moon Hydrangea prefers even moisture and protection from the hottest afternoon sun. Soil acidity can shift its flower color, making it a living indicator of the ground beneath it.",
        "highlights": ["Color responds to soil pH", "Excellent dried flower", "Prune after flowering"],
    },
    {
        "slug": "cedar-creek-lavender",
        "name": "Cedar Creek Lavender",
        "type": "Lavandula angustifolia",
        "location": "Cedar Valley, Washington",
        "status": "Peak season",
        "color": "Soft violet",
        "bloom_season": "Late spring to summer",
        "height": "45–75 cm",
        "sunlight": "Full sun",
        "water": "Low once established",
        "origin": "Mediterranean region",
        "image": "https://images.unsplash.com/photo-1499002238440-d264edd596ec?auto=format&fit=crop&w=1800&q=85",
        "accent": "blue",
        "summary": "Fragrant violet spires that thrive in lean soil, invite pollinators, and make a garden feel quietly Mediterranean.",
        "description": "Cedar Creek Lavender is happiest where drainage is sharp and sunlight is generous. Trim lightly after flowering to keep its rounded shape, and harvest the stems just as the first buds open for the strongest scent.",
        "highlights": ["Highly fragrant foliage", "Loved by bees", "Drought tolerant when mature"],
    },
    {
        "slug": "harbor-point-rose",
        "name": "Harbor Point Rose",
        "type": "Rosa ‘Harbor Point’",
        "location": "Atlantic garden, Maine",
        "status": "Resting",
        "color": "Blush pink",
        "bloom_season": "Late spring to first frost",
        "height": "120–180 cm",
        "sunlight": "Full sun",
        "water": "Deep weekly watering",
        "origin": "European garden hybrid",
        "image": "https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=1800&q=85",
        "accent": "rust",
        "summary": "A resilient garden rose with a soft blush scent, repeat flowers, and an easygoing habit for a sunny border.",
        "description": "Harbor Point Rose carries clusters of gently cupped blooms on arching stems. Feed in spring, water at the base, and remove faded flowers regularly to encourage another flush before the first frost.",
        "highlights": ["Repeat flowering", "Soft, classic fragrance", "Good for cutting"],
    },
    {
        "slug": "morning-glory",
        "name": "Morning Glory",
        "type": "Ipomoea purpurea",
        "location": "Cottage garden, Central America",
        "status": "In bloom",
        "color": "Sky blue",
        "bloom_season": "Summer to early autumn",
        "height": "2–4 m climbing",
        "sunlight": "Full sun",
        "water": "Moderate",
        "origin": "Tropical Americas",
        "image": "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1800&q=85",
        "accent": "blue",
        "summary": "A fast-growing climber whose trumpet flowers open with the first light and close into the afternoon.",
        "description": "Morning Glory quickly covers trellises and fences with heart-shaped leaves and clear, trumpet-shaped flowers. Sow it where it can climb freely, and give it a sturdy support from the start.",
        "highlights": ["Flowers open at dawn", "Excellent vertical cover", "Self-seeds readily"],
    },
    {
        "slug": "golden-sunflower",
        "name": "Golden Sunflower",
        "type": "Helianthus annuus",
        "location": "Open field, North America",
        "status": "Peak season",
        "color": "Golden yellow",
        "bloom_season": "Midsummer to early fall",
        "height": "150–300 cm",
        "sunlight": "Full sun",
        "water": "Deep, regular watering",
        "origin": "North America",
        "image": "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=1800&q=85",
        "accent": "amber",
        "summary": "A bright, architectural annual that turns toward the sun and leaves a feast for birds when summer ends.",
        "description": "Golden Sunflower makes a bold vertical statement with a single large flower head or branching sprays, depending on the variety. Plant successive sowings for a longer run of blooms and leave spent heads for finches.",
        "highlights": ["Loved by seed-eating birds", "Fast-growing annual", "Great cut flower"],
    },
    {
        "slug": "spring-tulip",
        "name": "Spring Tulip",
        "type": "Tulipa gesneriana",
        "location": "Formal garden, Central Asia",
        "status": "Spring bloom",
        "color": "Cherry red",
        "bloom_season": "Early to mid-spring",
        "height": "25–60 cm",
        "sunlight": "Full sun to light shade",
        "water": "Moderate, never soggy",
        "origin": "Central Asia and Türkiye",
        "image": "https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=1800&q=85",
        "accent": "rust",
        "summary": "A clean-lined spring classic that brings saturated color to beds just as the garden wakes up.",
        "description": "Spring Tulips grow from autumn-planted bulbs and prefer cool winters followed by bright, well-drained spring soil. Plant them in generous groups for a stronger visual rhythm and protect new shoots from hungry visitors.",
        "highlights": ["Plant bulbs in autumn", "Excellent in groups", "Many forms and colors"],
    },
    {
        "slug": "white-daisy",
        "name": "White Daisy",
        "type": "Leucanthemum vulgare",
        "location": "Meadow edge, Europe",
        "status": "In bloom",
        "color": "White and yellow",
        "bloom_season": "Late spring to summer",
        "height": "30–90 cm",
        "sunlight": "Full sun",
        "water": "Moderate",
        "origin": "Europe and temperate Asia",
        "image": "https://images.unsplash.com/photo-1551969014-7d2c4cddf0b6?auto=format&fit=crop&w=1800&q=85",
        "accent": "teal",
        "summary": "A meadow favorite with a sunny center, crisp petals, and an unfussy habit that suits informal planting.",
        "description": "White Daisy is a reliable perennial for meadow-style borders and cottage gardens. Remove the first wave of faded heads to encourage a second flush, or let some seed mature for a looser natural drift.",
        "highlights": ["Easy-care perennial", "Good meadow plant", "Attracts small pollinators"],
    },
    {
        "slug": "peach-peony",
        "name": "Peach Peony",
        "type": "Paeonia lactiflora",
        "location": "Cool border, eastern Asia",
        "status": "Resting",
        "color": "Apricot blush",
        "bloom_season": "Late spring",
        "height": "60–90 cm",
        "sunlight": "Full sun",
        "water": "Regular during growth",
        "origin": "China, Korea, and Siberia",
        "image": "https://images.unsplash.com/photo-1563241527-3004b7be0ffd?auto=format&fit=crop&w=1800&q=85",
        "accent": "rust",
        "summary": "A long-lived perennial with generous, ruffled blooms that return more confidently with every passing year.",
        "description": "Peach Peony settles slowly, then becomes one of the most dependable late-spring performers in the garden. Plant its eyes just below the soil surface, support heavy flowers early, and avoid moving an established clump.",
        "highlights": ["Can live for decades", "Scented cut flower", "Needs winter chill"],
    },
    {
        "slug": "pink-cosmos",
        "name": "Pink Cosmos",
        "type": "Cosmos bipinnatus",
        "location": "Sunny border, Mexico",
        "status": "In bloom",
        "color": "Rose pink",
        "bloom_season": "Summer to first frost",
        "height": "90–150 cm",
        "sunlight": "Full sun",
        "water": "Low to moderate",
        "origin": "Mexico and South America",
        "image": "https://images.unsplash.com/photo-1470509037663-253afd7f0f51?auto=format&fit=crop&w=1800&q=85",
        "accent": "teal",
        "summary": "Airy, dancing foliage and simple pink petals make this annual feel light, generous, and endlessly useful.",
        "description": "Pink Cosmos blooms for months when picked often, even in ordinary soil. It is an ideal bridge between a structured border and a wilder planting, with slender stems that move beautifully in a breeze.",
        "highlights": ["Long flowering season", "Thrives in lean soil", "Excellent for beginners"],
    },
    {
        "slug": "autumn-chrysanthemum",
        "name": "Autumn Chrysanthemum",
        "type": "Chrysanthemum morifolium",
        "location": "Autumn garden, China",
        "status": "Late season",
        "color": "Burnt orange",
        "bloom_season": "Late summer to autumn",
        "height": "30–90 cm",
        "sunlight": "Full sun",
        "water": "Regular, well-drained",
        "origin": "China and northeastern Asia",
        "image": "https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=1800&q=85",
        "accent": "amber",
        "summary": "A late-season color anchor that keeps borders vivid after summer’s softer flowers begin to fade.",
        "description": "Autumn Chrysanthemum offers a wide range of flower forms, from button blooms to full decorative heads. Pinch plants through early summer for branching, then let them build their final flower buds as days shorten.",
        "highlights": ["Brightens autumn borders", "Wide range of forms", "Pinch for bushier growth"],
    },
    {
        "slug": "moth-orchid",
        "name": "Moth Orchid",
        "type": "Phalaenopsis amabilis",
        "location": "Warm forest, Southeast Asia",
        "status": "Indoor bloom",
        "color": "White with gold",
        "bloom_season": "Winter to late spring",
        "height": "30–60 cm",
        "sunlight": "Bright, indirect light",
        "water": "Weekly, then drain well",
        "origin": "Southeast Asia and Australia",
        "image": "https://images.unsplash.com/photo-1566958769312-82cef41d19ef?auto=format&fit=crop&w=1800&q=85",
        "accent": "blue",
        "summary": "An elegant indoor orchid with arching stems and porcelain blooms that can last for months.",
        "description": "Moth Orchid prefers a warm room, filtered light, and an airy bark-based potting mix. Water thoroughly when the roots turn silvery, then let the plant drain completely before returning it to its place.",
        "highlights": ["Long-lasting indoor flowers", "Water when roots turn silver", "Reblooms with patient care"],
    },
]


def make_flower(slug, name, flower_type, location, status, color, bloom_season,
                height, sunlight, water, origin, image, accent, summary,
                description, highlights):
    return {
        "slug": slug,
        "name": name,
        "type": flower_type,
        "location": location,
        "status": status,
        "color": color,
        "bloom_season": bloom_season,
        "height": height,
        "sunlight": sunlight,
        "water": water,
        "origin": origin,
        "image": image,
        "accent": accent,
        "summary": summary,
        "description": description,
        "highlights": highlights,
    }


FLOWERS = [
    make_flower("lotus", "Sacred Lotus", "Nelumbo nucifera", "Temple ponds, India", "In bloom", "Rose pink", "July to September", "90–150 cm", "Full sun", "Aquatic, still water", "India and Southeast Asia", "https://images.unsplash.com/photo-1474552226712-ac0f0961a954?auto=format&fit=crop&w=1800&q=85", "teal", "India's national flower, floating above the water with a calm, architectural grace.", "Sacred Lotus roots in the mud while its leaves and flowers rise cleanly above the water. Grow it in a wide container or pond with warmth, full sun, and room for its spreading rhizomes.", ["National flower of India", "Thrives in warm ponds", "Fragrant summer bloom"]),
    make_flower("desi-rose", "Indian Rose", "Rosa indica", "Mughal garden, North India", "In bloom", "Crimson red", "October to March", "60–150 cm", "Full sun", "Deep weekly watering", "India and western Asia", "https://images.unsplash.com/photo-1496062031456-07b8f162a322?auto=format&fit=crop&w=1800&q=85", "rust", "A richly scented garden rose used in garlands, attar, celebrations, and everyday courtyards.", "Indian Rose prefers a bright position and fertile soil with good drainage. Remove faded blooms often, feed during active growth, and water at the base to keep the foliage healthy.", ["Excellent for rose water", "Fragrant cut flower", "Prune after flowering"]),
    make_flower("jasmine", "Jasmine", "Jasminum sambac", "Courtyard garden, South India", "Fragrant bloom", "White", "Warm season, year-round in tropics", "1–3 m climber", "Bright sun to partial shade", "Regular moisture", "South and Southeast Asia", "https://images.unsplash.com/photo-1596700810893-5b0a1f17d8b0?auto=format&fit=crop&w=1800&q=85", "blue", "Small white flowers with a powerful evening fragrance, woven into garlands across India.", "Jasmine is happiest in warmth, bright light, and a pot or border that drains freely. Pick the unopened flowers at dawn for garlands, or let the blooms open near a window after sunset.", ["Used in mogra garlands", "Strong evening fragrance", "Flowers repeatedly in warmth"]),
    make_flower("marigold", "Indian Marigold", "Tagetes erecta", "Festival garden, Maharashtra", "Peak season", "Saffron yellow", "October to February", "30–90 cm", "Full sun", "Moderate", "Mexico, naturalized in India", "https://images.unsplash.com/photo-1509223197845-458d87318791?auto=format&fit=crop&w=1800&q=85", "amber", "A cheerful golden flower central to Indian festivals, ceremonies, and bright seasonal borders.", "Indian Marigold is a forgiving annual that grows quickly from seed in warm weather. Pinch young plants for branching and remove spent heads to keep the flowers coming.", ["Popular festival flower", "Easy from seed", "Natural pest-deterrent companion"]),
    make_flower("hibiscus", "Red Hibiscus", "Hibiscus rosa-sinensis", "Tropical garden, Kerala", "In bloom", "Scarlet red", "Year-round in the tropics", "1–3 m shrub", "Full sun", "Regular moisture", "East Asia, widely grown in India", "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=1800&q=85", "rust", "A bold tropical bloom with a wide trumpet face and a strong place in Indian gardens and traditions.", "Red Hibiscus flowers best with warmth, sun, and evenly moist soil. Feed lightly during the growing season and prune after a flush to encourage fresh, flowering branches.", ["Attracts butterflies", "Used in पूजा and offerings", "Long flowering season"]),
    make_flower("sunflower", "Sunflower", "Helianthus annuus", "Open field, Karnataka", "Peak season", "Golden yellow", "June to October", "150–300 cm", "Full sun", "Deep, regular watering", "North America, widely cultivated in India", "https://images.unsplash.com/photo-1597848212624-a19eb35e2651?auto=format&fit=crop&w=1800&q=85", "amber", "A sunny annual that brings height, movement, and a feast for birds to the Indian summer garden.", "Sunflowers need direct sun and a deep root run. Plant successive sowings for a longer display, and leave the finished heads for parrots, finches, and other seed-eating birds.", ["Loved by seed-eating birds", "Fast-growing annual", "Great cut flower"]),
    make_flower("orchid", "Indian Orchid", "Dendrobium nobile", "Cloud forest, Sikkim", "Indoor bloom", "White and violet", "Winter to spring", "30–90 cm", "Bright, indirect light", "Weekly, then drain well", "Himalayan region and Southeast Asia", "https://images.unsplash.com/photo-1566958769312-82cef41d19ef?auto=format&fit=crop&w=1800&q=85", "blue", "An elegant Himalayan orchid with patterned petals and a preference for cool, clean mountain air.", "Indian Orchid varieties appreciate filtered light, airflow, and an airy bark mix. Let the potting medium dry slightly between waterings and protect it from harsh afternoon sun.", ["Himalayan native", "Long-lasting flowers", "Needs airy potting mix"]),
    make_flower("bougainvillea", "Bougainvillea", "Bougainvillea glabra", "Terrace garden, Rajasthan", "In bloom", "Magenta pink", "Winter to summer", "2–8 m climber", "Full sun", "Low once established", "South America, widely grown in India", "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1800&q=85", "teal", "A sun-loving climber that turns walls, gates, and terraces into sheets of vivid color.", "Bougainvillea flowers most freely when its roots are slightly restricted and its position is bright. Train young stems onto a support and avoid overwatering, which encourages leaves over color.", ["Thrives in hot climates", "Excellent wall cover", "Drought tolerant when mature"]),
    make_flower("plumeria", "Frangipani", "Plumeria rubra", "Coastal garden, Goa", "Fragrant bloom", "White and yellow", "April to September", "3–8 m tree", "Full sun", "Moderate, allow to dry", "Central America, naturalized in India", "https://images.unsplash.com/photo-1559563362-c667ba5f5480?auto=format&fit=crop&w=1800&q=85", "amber", "A temple-tree favorite with waxy petals and a soft fragrance that carries through warm evenings.", "Frangipani is happiest in sun and free-draining soil. It rests in cooler months, so reduce watering then and handle its milky sap with care.", ["Temple and lei flower", "Strong evening scent", "Suits warm coastal gardens"]),
    make_flower("champa", "Golden Champa", "Magnolia champaca", "Temple garden, Karnataka", "Fragrant bloom", "Golden yellow", "May to September", "8–15 m tree", "Full sun to light shade", "Regular when young", "India and Southeast Asia", "https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1800&q=85", "rust", "A golden, intensely fragrant flower associated with temple courtyards and monsoon-season air.", "Golden Champa grows into a graceful tree in warm, humid regions. Give young plants shelter, rich soil, and room to develop a broad crown over time.", ["Highly fragrant flowers", "Important temple flower", "Attracts night pollinators"]),
    make_flower("gulmohar", "Gulmohar", "Delonix regia", "Avenue tree, Delhi", "Summer bloom", "Flame orange", "April to June", "8–15 m tree", "Full sun", "Moderate once established", "Madagascar, widely planted in India", "https://images.unsplash.com/photo-1497250681960-ef046c08a56e?auto=format&fit=crop&w=1800&q=85", "rust", "A flamboyant avenue tree whose spreading crown turns hot-season streets into a canopy of flame.", "Gulmohar needs space, strong light, and well-drained ground. Its fern-like leaves create delicate shade while the orange flowers arrive before the heaviest monsoon rains.", ["Iconic summer avenue tree", "Wide spreading canopy", "Attracts nectar feeders"]),
    make_flower("palash", "Palash", "Butea monosperma", "Dry forest, Madhya Pradesh", "Summer bloom", "Flame red", "February to April", "8–12 m tree", "Full sun", "Low once established", "Indian subcontinent", "https://images.unsplash.com/photo-1509223197845-458d87318791?auto=format&fit=crop&w=1800&q=85", "amber", "The flame-of-the-forest, lighting up dry landscapes with red-orange flowers before the new leaves arrive.", "Palash is a hardy native tree for warm, dry regions. Its flowers are especially striking when the branches are briefly bare, and its nectar supports birds and insects.", ["Native Indian tree", "Supports local wildlife", "Known as flame-of-the-forest"]),
    make_flower("periwinkle", "Periwinkle", "Catharanthus roseus", "Home garden, Tamil Nadu", "In bloom", "Pink and white", "Year-round in warm climates", "30–60 cm", "Full sun to partial shade", "Low to moderate", "Madagascar, naturalized in India", "https://images.unsplash.com/photo-1490750967868-88aa4486c946?auto=format&fit=crop&w=1800&q=85", "teal", "A resilient little flower that keeps blooming through heat, pots, borders, and difficult garden corners.", "Periwinkle tolerates heat and short dry spells once established. Give it a bright position, avoid waterlogged soil, and trim lightly when it becomes leggy.", ["Heat tolerant", "Good container flower", "Blooms for much of the year"]),
    make_flower("chrysanthemum", "Chrysanthemum", "Chrysanthemum morifolium", "Winter garden, West Bengal", "Late season", "White and yellow", "October to January", "30–90 cm", "Full sun", "Regular, well-drained", "China, cultivated across India", "https://images.unsplash.com/photo-1508610048659-a06b669e3321?auto=format&fit=crop&w=1800&q=85", "blue", "A winter-season favorite with generous flower heads for balconies, borders, and festive arrangements.", "Chrysanthemums flower strongly when they receive bright light and cool nights. Pinch growing tips before midsummer for bushier plants, then let the final buds develop undisturbed.", ["Popular winter flower", "Many flower forms", "Excellent for arrangements"]),
    make_flower("dahlia", "Dahlia", "Dahlia pinnata", "Hill garden, Himachal Pradesh", "In bloom", "Coral orange", "July to October", "60–150 cm", "Full sun", "Regular, well-drained", "Mexico, cultivated in Indian hill stations", "https://images.unsplash.com/photo-1508808703027-4e8e8e8b1b72?auto=format&fit=crop&w=1800&q=85", "amber", "A layered showstopper that brings the drama of the hill garden into late summer and autumn.", "Dahlia thrives in fertile soil and regular picking. Stake tall varieties early, protect the tubers from standing water, and lift them in colder hill climates after frost.", ["Excellent cut flower", "Many flower shapes", "Pinch for fuller plants"]),
    make_flower("tulip", "Indian Tulip", "Tulipa gesneriana", "Spring garden, Kashmir", "Spring bloom", "Crimson red", "March to April", "25–60 cm", "Full sun to light shade", "Moderate, never soggy", "Central Asia, grown in Kashmir", "https://images.unsplash.com/photo-1520763185298-1b434c919102?auto=format&fit=crop&w=1800&q=85", "rust", "A crisp spring bulb celebrated in Kashmir for its jewel-like color and orderly rows of flowers.", "Indian Tulips prefer cool winters, bright spring light, and soil that drains quickly. Plant bulbs in autumn and allow the leaves to yellow naturally after flowering.", ["Kashmir spring favorite", "Plant bulbs in autumn", "Excellent in groups"]),
    make_flower("night-jasmine", "Night-flowering Jasmine", "Nyctanthes arbor-tristis", "Courtyard garden, Uttar Pradesh", "Night fragrance", "White and orange", "August to December", "2–10 m tree", "Full sun to partial shade", "Moderate", "Indian subcontinent", "https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1800&q=85", "blue", "Tiny white flowers with orange centers fall at dawn after filling the night air with perfume.", "Night-flowering Jasmine is a hardy small tree for warm gardens. Its flowers open after dusk and carpet the ground by morning, making it especially memorable near a courtyard or path.", ["Opens after sunset", "Strong night fragrance", "Traditional Indian garden tree"]),
]


@app.route("/")
def index():
    return render_template("index.html", flowers=FLOWERS)


@app.route("/flower/<slug>")
def flower_detail(slug):
    flower = next((item for item in FLOWERS if item["slug"] == slug), None)
    if flower is None:
        abort(404)
    return render_template("flower.html", flower=flower)


if __name__ == "__main__":
    app.run(debug=True)